### ISSUE TITLE
Can't load /imgs/white/minimize.png

### ISSUE THREAD

**Issue by majenkotech** [atarw/material-ui-swing#106]
Trying to use this on Ubuntu with OpenJDK 11.0.7 it fails to load `/imgs/white/minimize.png`.

I tracked this down to that one image being a 1-bit image, rather than RGBA or grayscale, and it *really* doesn't like that format.

For the time being I'm overlaying my own RGBA format of the same image over the content of the jar file, but it could do with being adjusted in the repo.

**Comment by vincenzopalazzo** [comment]
HI @majenkotech.

This bug was known in the pre-release_6.1 but I resolve it inside [this commit](https://github.com/vincenzopalazzo/material-ui-swing/commit/ab647e5d7e332834f1c364d1d2d6a9b8b4f12909)

This branch is only for the official release and not for the dev process, for see the developer condition you can look inside the development branch [vincenzopalazzo/material-ui-swing](https://github.com/vincenzopalazzo/material-ui-swing)

Some icon inside the project are also png, but I will update this with svg, with library https://jiconfont.github.io/swing

You can download the last version of the library here [Download](https://github.com/vincenzopalazzo/material-ui-swing/tree/development/libs)

If you are interested to change inside the library in the version 1.1.1 official you can see the [CHANGELOG.md](https://github.com/vincenzopalazzo/material-ui-swing/blob/development/docs/CHANGELOG.md)

**Comment by vincenzopalazzo** [comment]
Fixed in material-ui-swing-1.1.1-rc1, look here https://github.com/vincenzopalazzo/material-ui-swing/releases
