### ISSUE TITLE
Maven support

### ISSUE THREAD

**Issue by CesarCoelho** [atarw/material-ui-swing#39]
Hi, would it be possible to mavenize the project?

**Comment by atarw** [comment]
Yeah, I can definitely do this after work

**Comment by vincenzopalazzo** [comment]
Hello @CesarCoelho, I was born as an apprentice programmer studying in "ant" university, now it's been a while since I was studying "maven" as a construction system so I created a repo (to learn because I had never done so) of maven via [https://jitpack.io/#vincenzopalazzo/material-ui-swing](url) of my fork for project of material-ui-swing
It's been for educational purposes only and you can use it as long as it does not release its version.

ps: @atarw Excuse me if I always intrude but I'm just trying to learn, if I bother stop

**Comment by CesarCoelho** [comment]
Hi @vincenzopalazzo , I am a bit confused with the sentence:
"and you can use it as long as it does not release its version."
What does this mean? Is it still under the Apache License?

Maybe you can make a pull request here on github for @atarw to review and merge?

**Comment by vincenzopalazzo** [comment]
@CesarCoelho Excuse me I expressed myself very badly.
I meant that you can use mine as long as @atarw  it will not publish that of the official project.

Sorry if I expressed myself badly.

ps: I do not publish the pull because I know that @atarw  it will do much better

**Comment by CesarCoelho** [comment]
No problem, Grazie mille!

**Comment by atarw** [comment]
Haha you aren't intruding, don't worry about that.
Anyways, I mavenized the project, I'll look into uploading it into the Maven central repository this weekend since it would be easier to use that way

**Comment by CesarCoelho** [comment]
Hi @atarw , is it already available in Maven central repository? (I didn't check)
If so, I guess we can close this issue!

**Comment by atarw** [comment]
Oops I'm sorry it hasn't been done yet, life's been getting in the way :(
The next week will be fairly busy for me so I'll try to do it by Friday, sorry for the delay

**Comment by atarw** [comment]
Ultimately I've decided not to upload this to maven just yet because I don't think this look and feel is quite stable yet (still a lot of quirks) and I'd rather wait until it's more stable. I promise this will happen eventually!!

**Comment by CesarCoelho** [comment]
Alright, no problem! I will create a new issue as: "Upload to Maven Central", just so you won't lose track of it.
