### ISSUE TITLE
Upload to Maven Central

### ISSUE THREAD

**Issue by CesarCoelho** [atarw/material-ui-swing#48]
The project is already mavenized.
It can be uploaded to Maven central to make the resolution of dependencies much faster.
Related with this issue:
https://github.com/atarw/material-ui-swing/issues/39

**Comment by vincenzopalazzo** [comment]
Hello @CesarCoelho,
I have made some personal changes to the project (such as adding a component that is the same as Android Toast), but the project is the same and kept up to date on all the fixes made to the original project.

I protest using this [https://jitpack.io/#vincenzopalazzo/material-ui-swing/v0.9.4.5](url) since jitpack is not very expensive in mavenizing the projects then initializing and updating a project in repo comes at no cost.

I would like to say this also because the problem # 39 has been closed for a week and in this week no updates have been made to the project.

ps: Sorry for the intrusion

**Comment by zajkivsky** [comment]
+1

Could be great if you provide builds on central maven repository.

**Comment by vincenzopalazzo** [comment]
Hello @zajkivsky,

I think the motivation of @atarw [(here)](https://github.com/atarw/material-ui-swing/issues/39 ) is still valid and I think that the look and feel still contains oddities, the most recent update has corrected nullpointer, also it would be cool to add a method of setting styles easier (I'm working) before create the maven repository, but this is only my personal thought.

**Comment by vincenzopalazzo** [comment]
@CesarCoelho, @zajkivsky I'm happy to announce the official maven repository, look this [reference](https://search.maven.org/artifact/io.github.vincenzopalazzo/material-ui-swing/1.0.0/jar)

**Comment by CesarCoelho** [comment]
Cool, thanks!

**Comment by vincenzopalazzo** [comment]
I'm marking this issue of how resolved and I'm closing it.
