### ISSUE TITLE
Strange effect when hovering JCombobox

### ISSUE THREAD

**Issue by Reap00r** [atarw/material-ui-swing#64]
The combobox react a little bit strange
![GIFCombobox](https://user-images.githubusercontent.com/4528294/54111111-643f0680-43e3-11e9-95e6-a1e4f42ea336.gif)

I think it is good that it changes the color when you hover over it. But I think it should change it back to the default color (white) when you leave the element. Additionally, there are strange black lines / bars when you hover over it. I have really no clue how this can happen, but you can see it pretty well in that gif.

**Comment by atarw** [comment]
Closing as it seems to be fixed

**Comment by Reap00r** [comment]
@vincenzopalazzo, @atarw 
Sorry bothering you again, but I just checked out your new fixes and for me it seems like it didn't fix (all) problems with the graphical issues. In my example I hover over a datechooser, but even when hovering over a combobox the same problem happens.
![GIFComboboxStillNotWorking](https://user-images.githubusercontent.com/4528294/54813032-e6091c80-4c8c-11e9-9cdc-ae44ae8590ff.gif)

**Comment by vincenzopalazzo** [comment]
Hi @Reap00r,
Don't apologize, we all want to make the project more robust and more beautiful, thanks for your help.

I didn't release the update right away, but I tested it and released the update only after being sure that it was displayed correctly this is what I see
![gitf](https://media.giphy.com/media/n5HifvVOT2HE0bQLeU/giphy.gif)
![Selection_032](https://user-images.githubusercontent.com/17150045/54815859-2e2b3d80-4c93-11e9-90d7-c244afa98dc6.png)
![Selection_031](https://user-images.githubusercontent.com/17150045/54815860-2ec3d400-4c93-11e9-9a1d-45e3a7ec7f5e.png)

I have an idea on what can cause your problem but first I could ask you politely if starting the demo you see your constituents in the same way? If you let me know that for this start work on it

**Comment by Reap00r** [comment]
Hi @vincenzopalazzo,
I can see in your example that it is working.
However, I pulled the current project (material ui) and started the demo and tried it:
![GIFHover1](https://user-images.githubusercontent.com/4528294/54904057-b3099780-4edd-11e9-8fad-548faf51430f.gif)
![GIFHover2](https://user-images.githubusercontent.com/4528294/54904072-bac93c00-4edd-11e9-8dad-71bae30bde66.gif)

Maybe this only happens in the current Material look and feel and not in your project?
Thanks for your help.

**Comment by vincenzopalazzo** [comment]
Hi @Reap00r,
I added this fix to @atarw project, now I pull the project and I see this
![No bug](https://media.giphy.com/media/8vOETXjb2fjB4qiEyt/giphy.gif)

On linux this problem does not exist, you use windows if I remember correctly right?

Can you give me time until tonight so I try to see if this bug is present on windows?

My version and that one goofy are perfectly aligned, I pay a lot of attention not to bring new bugs for my distraction in his project also because I'm just a contributor and I don't have direct access to the project and it's very difficult then to find bugs if I don't pay attention to what I introduce.

This evening I hope to resolve

**Comment by Reap00r** [comment]
Hi @vincenzopalazzo,
sure, take the time you need to fix it :)
And yes, I am using windows 10.

**Comment by vincenzopalazzo** [comment]
@Reap00r thanks I will let you know

**Comment by vincenzopalazzo** [comment]
Hi @Reap00r,

I would like to say something, "**May windows be cursed**" :)

I can't fix the bug in the evening, I have a bug to fix by tomorrow about the development of a blockchain parser because I have a deadline, if @atarw doesn't have time or if he wants me to take care of it I could wait until the end of this week, I promise which I will do my best to release the fix and change the JXTablePane icon by Sunday evening.

Meanwhile, do you mind reviewing your open issues and closing those that have been resolved with updates?
And also you can open this issue for the problem with a *[Windows]* label, thanks?

**Comment by Reap00r** [comment]
Hi @vincenzopalazzo,
I feel you in regards of windows :D but I guess every OS has its quirks ;)
no problem, just do it whenever you have the time to fix it. I am glad you are taking the time to do that anyway :)
I opened an additional issue for this with Windows in its title

**Comment by vincenzopalazzo** [comment]
@Reap00r, Mine was just a way to joke :)

**Comment by atarw** [comment]
I'll be pretty busy until the end of the week too but after that I can try to work on it!
