### ISSUE TITLE
Option 1 (Animated) in Demo Application is not animated

### ISSUE THREAD

**Issue by MJ-DEV91** [atarw/material-ui-swing#89]
Hi.
There is a menu (Option 1 (Animated)) in the demo application and I think it's supposed to be animated, but when I click on it, there is no animation. Did I miss something?

**Comment by vincenzopalazzo** [comment]
Hi @MJ-DEV91,

I think that we missed something :).

I'm more secure the not exist *NOW* the Animation on the MenuItem, or to put it better now the MenuItem are all animated because by default all have the mouse hover enable.

A year ago the mouse hovers not is enabled by default on the component. Sorry, I think it my error in the demo, I will remove the text inside the demo.

ps: if you have any idea to how add animation to the component, give me a mail to vincenzopalazzodev@gmail.com for discussing it :)
