### ISSUE TITLE
Docs needed

### ISSUE THREAD

**Issue by edpmath** [atarw/material-ui-swing#97]
Where can I find documentation about the library?

**Comment by vincenzopalazzo** [comment]
Hi @edpmath,

Sorry for the delay.

Unfortunately, we don't have the documentation, because there are some motivation, like:

- We are developers open-source without pay for this work, this will do this work because it is cool developing new system but we have other work out of this project and we don't have time to build a good documentations alienated with code .

- I'm trying to implement the system to render simplest the using of material-ui-swing and some customization, I have called this system MaterialTheming and this is a first example of using to community https://github.com/TheRolfFR/MaterialDarkPinkTheme.

Also, I'm intension to preparing an article to presentation of MaterilaTheming to the world.


Also, I'm trying to create a little of documentation with the answer inside the issues, so if you have a problem or you have some intention to implement an style I can help you. 
You can open s issues or you can send me an email (vincenzopalazzodev@gmail.com)

So, you can look the documentation inside other issues with tag doc, you can look here [vincenzopalazzo/material-ui-swing](https://github.com/vincenzopalazzo/material-ui-swing/issues?utf8=%E2%9C%93&q=label%3Adoc) and [atarw/material-ui-swing](https://github.com/atarw/material-ui-swing/issues?utf8=%E2%9C%93&q=label%3Adoc+)

to conclude with the version 1.1.1 I will add the javadoc (very util for MaterialTheming), you can consulting it inside [this branch](https://github.com/vincenzopalazzo/material-ui-swing/tree/development/docs).
At the moment you can clone the branch and you can run the index.html

I hope to help you with this answer.

PS: I'm active also on stackoverflow, for material-ui-swing you can use this tag 

java, material, swing, look-and-feel

**Comment by vincenzopalazzo** [comment]
Hi @edpmath javadoc is out  https://vincenzopalazzo.github.io/material-ui-swing/ with [material-ui-swing 1.1.1 pre-release6.1](https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/v1.1.1-prelease)

**Comment by vincenzopalazzo** [comment]
I'm marking this issue of how resolved and I'm closing it.
